twig:
    file_name_pattern: '*.twig'
    # config/packages/twig.yaml
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        strict_variables: true
knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'

